#!/usr/bin/env bash

cd restaurant-tinder-app/src
npm install
npm install react-router-dom
npm install --save styled components
npm install react-icons --save
npm install react-tinder-card --save
npm install react-rating-stars-component --save
npm install reactstrap
npm install rc-slider
npm install react-select-search
npm install fuse.js
npm install use-position

npm start